# Generated by Django 5.0 on 2024-05-20 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_exercise_delete_training'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='body_part',
        ),
        migrations.AddField(
            model_name='exercise',
            name='part',
            field=models.CharField(choices=[('klata', 'Klata'), ('plecy', 'Plecy'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('barki', 'Barki'), ('nogi', 'Nogi'), ('cardio', 'Cardio')], default='data', max_length=10),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('exercises', models.ManyToManyField(to='trainings.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
